### ISSUE TITLE
AR nigation crash

### ISSUE THREAD

**Issue by mingtsz** [mapbox/mapbox-vision-android-teaser#69] opened 2019-05-19 18:22 UTC
I try to do some app follow:
https://docs.mapbox.com/android/vision/examples/basic-blue-line-ar-navigation/
When I run the app module, the app crashes
then will show:

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 4149
    java.lang.RuntimeException: Unable to resume activity {com.example.myapplication/com.example.myapplication.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3784)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property application has not been initialized
        at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:157)
        at com.mapbox.vision.VisionManager.create(Unknown Source:2)
        at com.example.myapplication.MainActivity.onResume(MainActivity.java:105)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
Application terminated.

i don't know how to fix it.

**Comment by yunikkk** [comment] 2019-05-20 13:02
Hello, you'll need to follow basic installation instructions at
https://vision.mapbox.com/install/ and
https://docs.mapbox.com/android/vision/overview/

Seems you need to init VisionManager, eg. add `VisionManager.init(this, getResources().getString(R.string.mapbox_access_token));`  to your Application.onCreate call

**Comment by mingtsz** [comment] 2019-05-20 14:49
I try you say but it doesn't work too
and show

> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 10073
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/base.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/base.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.myapplication-5EtkOmtSUuQyYahXxRajJQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]] couldn't find "libvision-sdk-wrapper.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.mapbox.vision.mobile.core.NativeVisionManager.<clinit>(NativeVisionManager.kt:28)
        at com.mapbox.vision.VisionManager.create(VisionManager.kt:177)
        at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:157)
        at com.mapbox.vision.VisionManager.create(Unknown Source:2)
        at com.example.myapplication.MainActivity.onResume(MainActivity.java:108)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

 couldn't find "libvision-sdk-wrapper.so"
I try any answer on Internet, but isdoesn't work, too.

**Comment by yunikkk** [comment] 2019-05-20 14:52
Can you show your build.gradle files and VisionManager calls?

**Comment by mingtsz** [comment] 2019-05-20 15:00
`
apply plugin: 'com.android.application'

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    mavenCentral()
    maven { url 'https://mapbox.bintray.com/mapbox' }

}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0@arr'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.22.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.22.0'
    implementation "com.mapbox.vision:mapbox-android-vision:0.3.0"
    implementation "com.mapbox.vision:mapbox-android-vision-ar:0.3.0"
    implementation "com.mapbox.vision:mapbox-android-vision-safety:0.3.0"
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.8.2"
    implementation "com.mapbox.mapboxsdk:mapbox-android-core:0.2.1"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`

**Comment by yunikkk** [comment] 2019-06-03 08:18
Sorry for the delay,

is this issue still happening for you?

**Comment by vladzima** [comment] 2019-07-18 10:40
Closing for now. Feel free to reopen if needed.

**Closed by vladzima** 2019-07-18 10:40 UTC

**Comment by Chandan55** [comment] 2021-08-13 13:26
Hi @vladzima  

Please check this issue in **Android 11**

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Mapbox.getInstance(applicationContext, getString(R.string.mapbox_access_token))
        requestWindowFeature(Window.FEATURE_NO_TITLE)
        setContentView(R.layout.activity_mapbox_navigation)
        navigationView.onCreate(savedInstanceState)
        navigationView.initialize(this@MapboxNavigationActivity)
        mapBoxNavigation()
    }


--------------------------------------------------------------------------

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.netquall.groundlink/info.netquall.main.MapboxNavigationActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3607)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3771)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:245)
        at android.app.ActivityThread.main(ActivityThread.java:8004)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8803)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3070)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3034)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:165)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:303)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:115)
        at info.netquall.main.MapboxNavigationActivity.onCreate(MapboxNavigationActivity.kt:38)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3580)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3771) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:245) 
        at android.app.ActivityThread.main(ActivityThread.java:8004) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
